import { note } from '@clack/prompts';
import OpenAI from 'openai';

import { getConfig } from './commands/config';
import { i18n, I18nLocals } from './i18n';
import { configureCommitlintIntegration } from './modules/commitlint/config';
import { commitlintPrompts } from './modules/commitlint/prompts';
import { ConsistencyPrompt } from './modules/commitlint/types';
import * as utils from './modules/commitlint/utils';

const config = getConfig();
const translation = i18n[(config?.GW_LANGUAGE as I18nLocals) || 'en'];

export const IDENTITY = 'Focus on writing Git commit messages as the author.';

const INIT_MAIN_PROMPT = (language: string): { role: string; content: string } => ({
    role: 'system',
    content: `${IDENTITY} Analyze 'git diff --staged' to write clear, concise commit messages. Guidelines:

Title (Summary):
- Use categorized tags (e.g., 'Removed:', 'Bug Fixed:', 'Added:')
- Strictly up to 50 characters, descriptive, no period
- Use backticks for file names/code changes
- Ensure summary accurately reflects the changes
- Consider the first line as the title

Description (in ${language}):
- Use markdown formatting
- Outline changes, files, and line numbers
- Use backticks for code elements
- Differentiate minor/major changes

${config?.GW_EMOJI ? 'Use GitMoji convention.' : 'No preface.'}
${config?.GW_DESCRIPTION ? 'Explain changes directly, no "This commit" phrases.' : 'Title only, no description.'}

Provide commit message with clear title-description separation.`,
});

export const INIT_DIFF_PROMPT: OpenAI.Chat.ChatCompletionUserMessageParam = {
    role: 'user',
    content: `diff --git a/src/server.ts b/src/server.ts
    index ad4db42..f3b18a9 100644
    --- a/src/server.ts
    +++ b/src/server.ts
    @@ -10,7 +10,7 @@
    import {
        initWinstonLogger();
        
        const app = express();
        -const port = 7799;
        +const PORT = 7799;
        
        app.use(express.json());
        
        @@ -34,6 +34,6 @@
        app.use((_, res, next) => {
            // ROUTES
            app.use(PROTECTED_ROUTER_URL, protectedRouter);
            
            -app.listen(port, () => {
                -  console.log(\`Server listening on port \${port}\`);
                +app.listen(process.env.PORT || PORT, () => {
                    +  console.log(\`Server listening on port \${PORT}\`);
                });`,
};

const INIT_CONSISTENCY_PROMPT = (translation: ConsistencyPrompt): { role: string; content: string } => ({
    role: 'assistant',
    content: `${config?.GW_EMOJI ? '🐛 ' : ''}${translation.commitFix}
${config?.GW_EMOJI ? '✨ ' : ''}${translation.commitFeat}
${config?.GW_DESCRIPTION ? translation.commitDescription : ''}`,
});

export const getMainCommitPrompt = async (): Promise<
    (
        | OpenAI.Chat.ChatCompletionSystemMessageParam
        | OpenAI.Chat.ChatCompletionUserMessageParam
        | OpenAI.Chat.ChatCompletionAssistantMessageParam
        | OpenAI.Chat.ChatCompletionToolMessageParam
        | OpenAI.Chat.ChatCompletionFunctionMessageParam
        | OpenAI.Chat.ChatCompletionCreateParamsNonStreaming
        | OpenAI.Chat.ChatCompletionCreateParamsStreaming
        | {
              role: string;
              content: string;
          }
    )[]
> => {
    switch (config?.GW_PROMPT_MODULE) {
        case '@commitlint':
            if (!(await utils.commitlintLLMConfigExists())) {
                note(`GW_PROMPT_MODULE is @commitlint but you haven't generated consistency for this project yet.`);
                await configureCommitlintIntegration();
            }

            // Replace example prompt with a prompt that's generated by OpenAI for the commitlint config.
            // eslint-disable-next-line no-case-declarations
            const commitLintConfig = await utils.getCommitlintLLMConfig();

            return [
                commitlintPrompts.INIT_MAIN_PROMPT(translation.localLanguage, commitLintConfig.prompts),
                INIT_DIFF_PROMPT,
                INIT_CONSISTENCY_PROMPT(commitLintConfig.consistency[translation.localLanguage] as ConsistencyPrompt),
            ];

        default:
            // conventional-commit
            return [
                INIT_MAIN_PROMPT(translation.localLanguage),
                INIT_DIFF_PROMPT,
                INIT_CONSISTENCY_PROMPT(translation),
            ];
    }
};
